language: ruby

rvm:
  - ruby-head
  - 2.1
  - rbx-nightly-19mode
  - jruby-head
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-nightly-19mode
    - rvm: jruby-head
    - rvm: jruby-19mode

before_install:
  - gem install bundler
